// Generated by CoffeeScript 1.7.1
(function() {
  window.onload = function() {
    document.getElementById('to').onclick = function() {
      var e, txt_str, united_txt;
      txt_str = document.getElementById('txt').value;
      try {
        united_txt = surfaces_txt_unite.unite(txt_str);
      } catch (_error) {
        e = _error;
        alert(e);
      }
      return document.getElementById('united').value = united_txt;
    };
    return document.getElementById('set_example').onclick = function() {
      var txt_str;
      txt_str = ajax.gets('examples/surfaces.txt');
      return document.getElementById('txt').value = txt_str;
    };
  };

}).call(this);
